name: pull-request
on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: 3 22 * * *
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - if: github.event_name == 'pull_request'
        name: Run 'pre-commit' hooks
        uses: dycw/action-run-hooks@latest
        with:
          submodules: false
          repos: |-
            pre-commit/pre-commit-hooks
      - if: github.event_name == 'pull_request'
        name: Run 'pre-commit' hooks
        uses: dycw/action-run-hooks@latest
        with:
          repos: |-
            pre-commit/pre-commit-hooks
  pyright:
    runs-on: ubuntu-latest
    steps:
      - name: Run 'pyright'
        uses: dycw/action-pyright@latest
        with:
          python-version: "3.12"
  pytest:
    env:
      CI: "1"
    name: pytest (${{matrix.os}}, ${{matrix.python-version}},
      ${{matrix.resolution}})
    runs-on: ${{matrix.os}}
    services:
      redis:
        image: ${{ matrix.os == 'ubuntu-latest' && 'redis/redis-stack:latest' ||
          '' }}
        ports:
          - 6379:6379
    steps:
      - name: Run 'pytest'
        uses: dycw/action-pytest@latest
        with:
          python-version: ${{matrix.python-version}}
          resolution: ${{matrix.resolution}}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        python-version:
          - "3.12"
          - "3.13"
          - "3.14"
        resolution:
          - highest
          - lowest-direct
    timeout-minutes: 10
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Run 'ruff'
        uses: dycw/action-ruff@latest
