name: push
on:
  push:
    branches:
      - master
jobs:
  publish:
    environment:
      name: pypi
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Build and publish package
        uses: dycw/action-publish@latest
        with:
          token-checkout: ${{github.token}}
          token-uv: ${{github.token}}
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Tag latest commit
        uses: dycw/action-tag@latest
        with:
          token-checkout: ${{github.token}}
          token-uv: ${{github.token}}
          user-name: github-actions-bot
          user-email: noreply@github.com
